export const FALLBACK_API_PROVIDERS = [
  {
    id: 'deepseek',
    name: 'DeepSeek',
    base_url: 'https://api.deepseek.com',
    default_model: 'deepseek-v4-flash',
    description: '深度求索官方兼容接口',
    custom: false,
  },
  {
    id: 'qwen',
    name: '通义千问',
    base_url: 'https://dashscope.aliyuncs.com/compatible-mode/v1',
    default_model: 'qwen-plus',
    description: '阿里云百炼 OpenAI 兼容接口',
    custom: false,
  },
  {
    id: 'zhipu',
    name: '智谱 GLM',
    base_url: 'https://open.bigmodel.cn/api/paas/v4',
    default_model: 'glm-5.2',
    description: '智谱开放平台兼容接口',
    custom: false,
  },
  {
    id: 'kimi',
    name: 'Kimi',
    base_url: 'https://api.moonshot.cn/v1',
    default_model: 'kimi-k2.5',
    description: 'Kimi 开放平台兼容接口',
    custom: false,
  },
  {
    id: 'siliconflow',
    name: '硅基流动',
    base_url: 'https://api.siliconflow.cn/v1',
    default_model: 'Qwen/Qwen2.5-72B-Instruct',
    description: 'SiliconFlow 多模型兼容接口',
    custom: false,
  },
  {
    id: 'custom',
    name: '自定义兼容接口',
    base_url: '',
    default_model: '',
    description: '填写任意公开 HTTPS Chat Completions 兼容接口',
    custom: true,
  },
]
